### ISSUE TITLE
Upload image through fusio

### ISSUE THREAD

**Issue by koswarabilly** [apioo/fusio#105]
i am trying to upload image to local mysql database through fusio.
first i convert the image to base64 string with my app then i send the base64 string where i put into the link as parameter like this : `http://192.168.88.158/upload?base64=/9j/4QD6RXhpZgAATU0....` but the fusio return me the fail message

![screenshot from 2017-12-08 09-06-47](https://user-images.githubusercontent.com/29243760/33747715-32c023dc-dbf7-11e7-9aac-f1e2c6fd959f.png)

what can i do?

**Comment by k42b3** [comment]
Hi, ok the problem here is that Fusio inserts every HTTP request into a log table, in your case the path of the request is too long. I would recommend to send the image in the HTTP body through a POST request. The body field allows much more characters. But we should handle this case better so I flag this issue as bug.

**Comment by koswarabilly** [comment]
thankyou @k42b3

**Comment by k42b3** [comment]
The latest release contains now a fix for this problem. If the request uri is to long we truncate the url to a fitting size so that no error occurs.
