### ISSUE TITLE
system hangs while running migration

### ISSUE THREAD

**Issue by devalexandre** [apioo/fusio#117]
I try run a migrate, but every stopd

https://gist.github.com/devalexandre/7f1fbd5bebc4b6286333d19c9667efd6

**Comment by k42b3** [comment]
Hi, I think the problem is that you try to reference the `fusio_user` table in your constraint but the `fusio_user` table is probably not available on your remote connection. So if you remove those `fusio_user` constraints your migration should work.

**Comment by devalexandre** [comment]
I need have a user_id in some tables

**Comment by k42b3** [comment]
I think having a user_id column is not a problem. The constraint i.e.: https://gist.github.com/devalexandre/7f1fbd5bebc4b6286333d19c9667efd6#file-migrate-php-L34 is only a problem which points to a table `fusio_user` which probably does not exist on the connection. Since your app and fusio should work on two different databases.

**Comment by devalexandre** [comment]
but I need use the table user, how I could make it?

**Comment by k42b3** [comment]
Mhh ok, I think this is currently not easy possible since if you use the deploy mechanism you need a separate database (since the migration tool adjusts the database according to your schema). So I can only imagine to use a user_id column without the database constraints.

**Comment by k42b3** [comment]
It looks like there is nothing more todo here, otherwise please feel free to reopen the issue.
