### ISSUE TITLE
Administrator user

### ISSUE THREAD

**Issue by j2l** [apioo/fusio#124]
I noticed there's another Administrator account but I don't know its password and if we can delete it.

**Comment by k42b3** [comment]
Hi, yes this is a special default Administrator which is used on installation. The password is random generated on installation so it is not possible to use this account. It would be difficult to delete this user since there are many recods (i.e. Consumer/Backend app) in the system which reference this user.

**Comment by j2l** [comment]
Oh, I see.
Thanks for the precision!
Solved
