### ISSUE TITLE
docker dev to prod

### ISSUE THREAD

**Issue by j2l** [apioo/fusio#125]
Is there a tutorial about deploying the dev container to a remote VPS using Kitematic and Docker?

**Comment by k42b3** [comment]
So besides our repo at https://github.com/apioo/fusio-docker we have at the moment no special documentation for the docker container setup. But since we are currently working on the documentation we will probably add a new chapter to explain the docker setup. Regarding Kitematic iam not sure whether we need a documentation for this I think it should be possible to somehow add our https://hub.docker.com/r/fusio/fusio/ image and then start this through the tool. But please let me know if you have any problems regarding this setup or where it would be useful to add a documentation.

**Comment by j2l** [comment]
I successfully run fusio locally using kitematic.
I'd like to "commit" these containers to a Docker VPS and wonder if there's an easy way. Docker evolved so much since the last time I used it (tutum). It's not my main task.

My previous workflow was building docker on VPS from image then import data, which is useless with containers. 
I guess it's now a local->repository->VPS or best local->repository->test->prod(VPS).
Docker Cloud "own node" is not for Mac. I have a Linux Mint (Ubuntu) machine. Should I use it for local and first node?
Oh, and I'm adding that I'd like to use OVH VPS, not Digital Ocean.
If you have experienced it, I'd love to have feedback :)

**Comment by k42b3** [comment]
Ok, the normal workflow which I would recommend is to trigger your docker build through a CI server like travis or jenkins and then deploy this image on your prod server. If you use our [fusio-docker](https://github.com/apioo/fusio-docker) image changes are automatically detected and the fitting migration files are executed on deployment. This works also for multiple environments like dev > testing > prod

Regarding OVH, if you are using a VPS I have only the experience that some virtual server dont support docker because of the underlying virtualization software but otherwise this should be no problem. Also if you use a single VPS you cant scale your service easily, you may want to take a look also at a dedicated container hosting solution like [google-cloud](https://cloud.google.com/kubernetes-engine/), etc. but of course this is also more expensive.

**Comment by j2l** [comment]
Thank you very much Christoph!
I really appreciate your GLOBAL help. 
I know it will help others too :)
So many developers just want to provide technical help (and sometimes just close ticket for inactivity ... on their side).
