### ISSUE TITLE
Trying to use a library

### ISSUE THREAD

**Issue by theraw** [apioo/fusio#127]
hi

i'm trying to use `php-ovh` api library `https://github.com/ovh/php-ovh`
i created a test `.php` file with this content
```
<?php
require '/hostdata/********/public_html/src/ovh/lib/autoload.php';
use \Ovh\Api;
use GuzzleHttp\Client;

//////////////////////////////////////////////////////////
$applicationKey = "**********************";
$applicationSecret = "************************";
$consumer_key = "******************************";
//////////////////////////////////////////////////////////
$endpoint = 'ovh-ca';
//////////////////////////////////////////////////////////
$cloud = '*******************************************';

// Get available resources.
$conn = new Api(    $applicationKey,
                    $applicationSecret,
                    $endpoint,
                    $consumer_key);
$get = $conn->get('/cloud/project/'.$cloud.'/quota');
print_r($get);
```

I tired to execute it from fusio dashboard but i got no response :/ as i see from here it just keeps loading.. 
![image](https://user-images.githubusercontent.com/32969774/35890846-a7a5897e-0ba1-11e8-8276-f32339e731ea.png)

i think isn't possible to load ovh api like this? 

What i'm doing is related to openstack not directly to ovh so i'm ok even if is possible to use https://github.com/apioo/fusio-adapter-openstack for this, 
but i tried and i wasn't able to understand how to use it! i also tried your test files but still i wasn't able to understand how to use it!.
Maybe can you please give a simple clean example how to use it?! i also was searching maybe was explained to docs but i didn't found something about it..

**Comment by k42b3** [comment]
Hi, so if you build an action you cant use i.e. print_r since this does not return valid JSON. Please take a look at the [example todo](https://github.com/apioo/fusio/blob/master/src/Todo/collection.php) action. So you need to use i.e.:

```
return $response->build(200, [], [
    'response' => $get,
]);
```

to set a proper response. Fusio uses also composer so you can simply use `composer require ovh/ovh` inside the Fusio main directory so you dont need to inlcude the autoloader in the action. It would be also possible to create a new `fusio-adapter-ovh` which wraps this library, then you only need to create a connection in the backend and then can access the API in an action through: `$connector->getConnection('OVH-Connection');`

For OpenStack it depends on your use case but at first you need to create i.e. an open stack compute connection. Then you can use this connection in your action i.e.:

```
$compute = $connector->getConnection('OpenStack-Connection');

$flavor = $compute->createFlavor([
    'name'  => '{flavorName}',
    'ram'   => 128,
    'vcpus' => 1,
    'swap'  => 0,
    'disk'  => 1,
]);

return $response->build(200, [], [
    'success' => true,
]);
```

**Comment by theraw** [comment]
i did some different test with print_r before it worked, but was just for testing purposes and so i didn't tried to setup with a proper response/router etc..

so to use 
```
$compute = $connector->getConnection('OpenStack-Connection');
...
```
first i need to create a connection at `resources/connections.yaml` right?
there is no example for openstack however i tried something like this
```
OpenStack-Connection:
  class: Fusio\Adapter\OpenStack\Connection\Compute
  config:
    auth_url: "https://auth.cloud.ovh.net/v2.0"
    region: "GRA3"
    user_id: "NSseFxehDBxd"
    user_password: "******************************"
    project_id: "b36f60175e81461487af7e854af0f398"
```

but i'm getting errors like 
```{"error": {"message": "The resource could not be found.", "code": 404, "title": "Not Found"}}```

i see from your tests a url which have one "AUTH_" https://github.com/apioo/fusio-adapter-openstack/blob/master/tests/Connection/ApiTestCase.php#L46

the code which is after `AUTH_` it seems to be my project ID but i already have set that in `project_id:` 

However this is how can i connect openstack with `php-opencloud`
```
<?php
require 'vendor/autoload.php';

use OpenCloud\OpenStack;

$client = new OpenStack('https://auth.cloud.ovh.net/v2.0/', array(
    'username'   => 'NSseFxehDBxd',
    'password'   => '**********************************',
    'tenantName' => '**********************'
));
$compute = $client->computeService('nova', 'GRA3');
$client->authenticate();
print_r($client->getCatalog()->getItems());
```
So it works. But when i try to use the Compute `Class` at `connections.yaml` and when i try to `php bin/fusio deploy`
i get that err
```
- [FAILED] connection OpenStack-Connection: Client error: `POST https://auth.cloud.ovh.net/v2.0/auth/tokens` resulted in a `404 Not Found` response:
{"error": {"message": "The resource could not be found.", "code": 404, "title": "Not Found"}}
```
i'm doing something wrong or ?

**Comment by k42b3** [comment]
Hi, yes so youre configuration looks right. I think the problem is actually the options array format of the opencloud lib. So basically we use the options format from the [openstack sample](https://github.com/php-opencloud/openstack/blob/master/samples/compute/v2/flavors/create_flavor.php). We could also easily change the options format in the [adapter](https://github.com/apioo/fusio-adapter-openstack/blob/master/src/Connection/ConnectionAbstract.php) but Iam wondering what is the currently used format.

In our test case we unfortunately dont send actual requests to an openapi endpoint so this is only a dummy test. It would be great if we could setup an openstack server on travis but Iam currently not aware of any test API implementation which we could use.

**Comment by theraw** [comment]
to try to change adapter settings idk about that because this is somehow class under class i don't have that much knowledge to try it by myself...

But i can do something else, i can provide you access to my ovh public cloud so you can use that for testing, but you should know that i don't have full admin access, i just own a project in their openstack and i have access to create/remove machines, containers, images, volumes. but i don't have access for flavors..

So if you want to test it let me know a way how i can talk with you, facebook, discord or whatever!

**Comment by theraw** [comment]
I just sended you one email. title is "github.com/apioo/fusio/issues/127"

**Comment by k42b3** [comment]
Ok, thanks, I have received your mail. If I find the time in the next days I will try to test the open stack adapter, which should then resolve those issues. I think it basically comes down to use the correct options array format but I will let you know if I know the solution.

**Comment by theraw** [comment]
Okay thank you!
