### ISSUE TITLE
Little urgent guys Admin password :

### ISSUE THREAD

**Issue by iakk** [apioo/fusio#135]
Hi,

I am new in Fusio and really appreciate this project . i recently installed and facing problem please help. 

Problem: i recently installed Fusio in shared hosting by softaculous. but when ever i try to login with admin user name password i am not able to login. is changing password will be solution or another know issue please help.and if changing password will help how i can reset it, or change it in data base means which type of encryption i should set in db password field. when i change it .

early help is appreciated.

Thanking You,

Regards,
iakk

**Comment by k42b3** [comment]
Hi, so we have an issue #119 where a user has also problems with Fusio on softaculous. I have tried to debug the problem but it looks like Fusio is not correctly configured there. So I think you can not login because the backend app cant send requests to the backend api. In general it is possible to run Fusio on a shared hosting (http://fusio.readthedocs.io/en/latest/installation.html#shared-hosting) but it is recommended to use a host where you have access to the CLI so you can properly install fusio.

**Comment by k42b3** [comment]
I will close this issue since there is nothing more we can do here. Please reopen the issue if you think there is still a problem here.
