### ISSUE TITLE
A Very Severe Bug!!!

### ISSUE THREAD

**Issue by LaserStony** [apioo/fusio#164]
I Encountered a Serious Bug. I can access and create the Actions, Routes, Connections, Dashboard etc without logging in... Please Look into it ASAP!!.
![getting-started-project](https://user-images.githubusercontent.com/34425251/41978010-476ae15a-7a3a-11e8-93ec-c7f63304a15a.gif)

**Comment by chriskapp** [comment]
@LaserStony, Iam confident that the latest release fixes this issue but since it is an important topic could you please verify that the latest release fixes the problem. Then I would close this issue and recommend the new version for everyone.

**Comment by LaserStony** [comment]
@chriskapp Ok. Will Look into it..

**Comment by LaserStony** [comment]
@chriskapp, Now I don't get the Details but still getting the View. I opened http://mywebsite.com/public/fusio/#!/routes

![image](https://user-images.githubusercontent.com/34425251/42162077-de9cf79a-7e16-11e8-94ab-e0cdd6e96be2.png)

**Comment by chriskapp** [comment]
@LaserStony ok, yes this is ok since it is only the HTML view but no data gets transfered from the server. If you take a look at the browser developer console you should see lots of HTTP 401 responses indicating that the request is not authorized. If you think there is still a problem please let me know but for now I will close this issue.
