### ISSUE TITLE
Deploy - Force flag executes all migrations

### ISSUE THREAD

**Issue by christoph-bessei** [apioo/fusio#184]
The ```-f``` flag for ```fusio deploy``` (#140) currently executes all available migrations.
IMHO it would be better to force execute only the last migration, to avoid problems with older versions.
Example:
migration_v1 sets a column to "not null", migration_v2 (the current state) allows null values.
If```fusio deploy -f```` is executed, migration_v1 will convert all null values in this column to 0, '' or some other default value. This could cause problems with UNIQUE indexes (unique with multiple null rows is possible, but not with 0 or '').

**Comment by chriskapp** [comment]
Hi, in the latest 1.3 release we have moved our migration system to the [doctrine migrations](https://www.doctrine-project.org/projects/migrations.html) library which is a dedicated library to handle migrations. Because of this we also dont execute migrations on `deploy` anymore. You need to use a separate migration command i.e.:

```
php bin/fusio migration:migrate --connection=System
```

to execute migrations. The doctrine migration system is more powerful then our previous implementation and allows you i.e. to re-execute specific migrations, execute dry-runs and generate all SQL queries. Please let me know if you have any further questions regarding the change.

**Comment by christoph-bessei** [comment]
Ah sorry, I missed that change!
I will check the new release and reopen the issue, if it's still a problem. Thanks for your fast feedback (as always)!
