### ISSUE TITLE
configuration.php contains misleading instructions regarding mod_rewrite

### ISSUE THREAD

**Issue by marcosandresacevedo** [apioo/fusio#22]
Hello,

I believe the configuration.php file contains a misleading comment regarding whether or not the 'index.php/' value needs to be set in psx_dispatch key.

It says:

> // The input path 'index.php/' or '' if you use mod_rewrite

I have mod_rewrite enabled and the Virtual Hosts configuration file properly configured (AllowOverride All) for the .htaccess file to apply rules so I found myself assuming this key needed to be set as '' .

This however causes an authentication error when I try to login to the backend.htm. I turned on debug for the psx_debug setting and the the following error is sent back on the response:

PSX\\Framework\\Loader\\InvalidPathException

After trying to figure out many things I reverted the psx_dispatch setting to have the 'index.php/' value set and I could finally login properly.

I don't know enough about the PSX Framework to know if this is the expected behavior or when should the value of psx_dispatch be set to '', but if someone reads the comment it might lead them to unnecessarily setting '' to the psx_dispatch key and locking themselves out unable to use the software without understanding why it could be misconfigured.

**Comment by k42b3** [comment]
Hi, the `psx_dispatch` parameter tells the framework whether request uris look 
like i.e.:

 * `/index.php/backend/token` or 
 * `/backend/token`

so whether `index.php/` is used or not. If you set the parameter to `''` you also
need to request each endpoint without the `index.php/`. But by default the 
backend app uses `/index.php/backend/token` since this works also without mod_rewrite.

If you take a look at the backend html file there is a line

```
fusioProvider.guessFusioEndpointUrl(false);
```

If you change there `false` to `true` all API calls are made without `index.php/`
thus you can also set `psx_dispatch` to `''`.

But your point is correct, it should not be possible to break the application through
this setting. For the next release we try to develop a fix that handles both cases.

**Comment by marcosandresacevedo** [comment]
Thank you. That clears things up a bit. I don't think I found anywhere in the documentation that  `fusioProvider.guessFusioEndpointUrl(false);` should have been set to `true` as well so intent remained unclear.

**Comment by k42b3** [comment]
We have added a comment to the `index.htm` which explains the `guessFusioEndpointUrl` argument
