### ISSUE TITLE
Fusio UI

### ISSUE THREAD

**Issue by alexfok007** [apioo/fusio#221]
Hi ,after use it for few weeks this very good backend platform.

However, there have 2 points.

For the fusio UI after login a period and when the token expired. The web will not redirect to login page. Suggest to add a checking redirect back to login page.

The file index.htm i think now a days people use .html instead. 

Most default apprached setting dont add index.htm

**Comment by chriskapp** [comment]
Hi, thanks for the feedback. Regarding the token expiration, we have already such a redirect logic (https://github.com/apioo/fusio-backend/blob/master/app/app.js#L119), but it does not work in all case. So we have this on our todo list and will fix this in the future.

Regarding the renaming of the `index.htm` file this is indeed a good idea, since the documentation and developer app already use `.html` as file extension.

**Comment by alexfok007** [comment]
How about add checking on each request? If a request got fail. Redirect to login page.

**Comment by chriskapp** [comment]
So we have renamed the `index` file to `index.html`. Regarding the redirect, we have plans to update our backend app to the latest Angular version. Then we can also handle the redirect properly, since we have all this information inside the JWT we only need to check this before the token expires.

**Comment by chriskapp** [comment]
I will close this issue since everything here is solved.
