### ISSUE TITLE
Is it possible to add additional parameters when registering a new user?

### ISSUE THREAD

**Issue by cosmastech** [apioo/fusio#226]
My client requires that when a user is created, they need to also have some other parameters recorded (first name and last name, for instance).  Is this possible? What would be the best way to handle it?  I didn't see anyway to extend/override the user registration class.

**Comment by alexfok007** [comment]
Currently my solution is created a new connection to connecting fusio database. (Dont know why "system" connection blocked fusio data table by default.)

In the route connect to fusio db and my Apps db . Do copy user id, name , email to my Apps database if not exist.

**Comment by chriskapp** [comment]
Hi, this is a request which we receive often and I think we should implement a general soluton so that its easy to extend the existing user table with additional columns. Currently as workaroung you can use the way which @alexfok007 described.

> Currently my solution is created a new connection to connecting fusio database. (Dont know why "system" connection blocked fusio data table by default.)

@alexfok007 we do this to handle the migrations properly. If you execute a migration on the System connection you only want to change the tables of your app and not the tables of Fusio.

**Comment by chriskapp** [comment]
The latest release contains now a feature called user attributes which allows to define arbitrary attributes for a user. More information at our manual: https://fusio.readthedocs.io/en/latest/concept/user_attributes.html
Therefor I will close this issue.
