### ISSUE TITLE
Feature request: User "grouping" with assigned scopes

### ISSUE THREAD

**Issue by EvoPulseGaming** [apioo/fusio#257]
I have a client, that will control the entire database, the client has employees that can only delete/create rows. I plan on using fusio's builtin user management for this.

The program I am writing for the client will allow them to do anything allowed without going into the backend, this includes adding/removing employees as users and setting the scope.

MODIFIED INTO A FEATURE REQUEST:

I have a feature suggestion:

Allow users to be created as children of another user. 
Allow admin to create groups with each owns inherited scopes (admin, accountant, supervisor, painter, carpenter ect)
Allow admin user to generate "invite codes" for each subgroup, that employees can use to register themselves.

(I'm sure once implemented this will work by default, but have an API to pull the user's parent user's ID

For example, I have 5 businesses that use my fusio backend. Each business, can create their own users (employees), which are automatically linked to the primary account, with inherited scopes.

**Comment by chriskapp** [comment]
Hi, so building a "Property management system" should be possible. To use the user registration system you can directly use the http://demo.fusio-project.org/internal/#!/api/consumer/register and login endpoint. Then you only need to build the fitting database schema and backend endpoints to create your entities. In general everything which you can do with the backend is also possible via the API. If you build youre app in PHP/C++ you can also use the internal API of Fusio, otherwise it would be easy possible to write a simple javascript app. So I hope this helps you a little bit to continue.

**Comment by EvoPulseGaming** [comment]
I feel so stupid for not seeing all these endpoints!!!! This is perfect.

**Comment by EvoPulseGaming** [comment]
I have a feature suggestion:

Allow users to be created as children of another user.

For example, I have 5 businesses that use my fusio backend. Each business, has  can create their own users (employees), which are automatically linked to the primary account, with inherited scopes.

**Comment by chriskapp** [comment]
This is an interesting idea. I had also the idea to build a "user group" feature so that every user is assigned to a user group and you can assign scopes to the group and every user which is assigned to the group inherits those rights. I think this is basically the functionality which you need for your use case, so you could create for each business a specific group. But then it must be possible to specify the group if the user registers or we need something like a default group where every user gets automatically assigned.

**Comment by EvoPulseGaming** [comment]
I've contacted them, I'll let you know how it goes

**Comment by EvoPulseGaming** [comment]
If the "admin" register a "employee", the admin should be able to place them in a group during creation.

If a "user" registers themselves, and are trying to join a business, the business could have an "invite code" that would identify them (each group could have a unique invite code)

**Comment by chriskapp** [comment]
With the next 2.0 RC release we will introduce a new role feature which allows us to assign a user to a specific role and at the role we can configure which scopes a user should receive.

**Comment by EvoPulseGaming** [comment]
So cool!!
