### ISSUE TITLE
SQL select action

### ISSUE THREAD

**Issue by chriskapp** [apioo/fusio#260]
We need a general SQL action where the user can simply provide an SQL query and we use the response to build an API. The action could look like:

![sql-select](https://user-images.githubusercontent.com/2505846/64888854-41c8c700-d66c-11e9-8ca9-64201bd7d96e.png)

**Comment by chriskapp** [comment]
Implemented in the latest release

**Comment by ratsey** [comment]
The COUNT(*) SQL that's added to the provided SQL doesn't work with MariaDB (and I'm assuming MySQL) due to:

> Unlike a subquery, a derived table must have a an alias so that you can reference its name later in the query. If a derived table does not have an alias, MySQL will issue the following error:
> Every derived table must have its own alias.

If I supply a simple query such as 

`SELECT * FROM pre_order`

I get that error since Fusio is attempting to execute

`SELECT COUNT(*) AS cnt FROM (SELECT * FROM pre_order)`

Adding an alias for the derived table resolves the error:

`SELECT COUNT(*) AS cnt FROM (SELECT * FROM pre_order) T`

**Comment by chriskapp** [comment]
Hi, so there is already a fix on the master (https://github.com/apioo/fusio-adapter-sql/blob/master/src/Action/SqlSelect.php#L70) but there was no tag yet. So I have just tagged a new version 3.0.9 which you can install with `composer update fusio/adapter-sql` with the next release this is then automatically included.
