### ISSUE TITLE
Add fusio_audit and fusio_app_token also to the log rotate command

### ISSUE THREAD

**Issue by kvnlwlls** [apioo/fusio#270]
Christoph - 

It would be very helpful to provide bin/fusio commands, similar to the bin/fusio command "system:log_rotate", which will clean out or archive audit and application tokens.

-Kevin

**Comment by chriskapp** [comment]
Hi, sure I think we can also add this to the existing `system:log_rotate` command so that also the `fusio_audit` table is cleared and archived if you invoke the `system:log_rotate` command. Regarding the `fusio_app_token` table I think this is more difficult to archive since we cant empty the table since it contains the list of active access tokens, we could only remove "expired" token entries but this should be then handled probably in a different command.

**Comment by chriskapp** [comment]
So we have added the fusio_audit table to the `system:log_rotate` command. The fusio_app_token table is now handled by the `system:clean` command which removes expired tokens from the table. This should cover both use cases. The changes are then included in the next release.
