### ISSUE TITLE
Feature: individual scopes for get,post,put,delete routes

### ISSUE THREAD

**Issue by EvoPulseGaming** [apioo/fusio#271]
Change the current scopes to "general" type (technically this already is)
Add a individual scope section to each type of route.

Reasoning: for example, I may allow a worker to view work orders,but not allow them to create work orders. or allow an accountant to view paid items, but not create paid items.

 Currently we would have to create two routes for this.

**Comment by chriskapp** [comment]
Hi, so this is currently possible but in another way. If you define a scope you can declare at the scope which routes and method (GET, POST, etc.) is allowed. The user can then use with this scope only the assigned routes and request methods. So you could create a scope `work_order.view` and `work_order.create` then assign those scopes to the fitting user. The scopes can be configured under `Consumer / Scopes`.

**Comment by EvoPulseGaming** [comment]
I noticed something like this if you use the backend, you can go through the scopes and enable/disable each part of a route.

However, if I want to add "consumer", or "backend" I cannot do it this way, I have to add it to the route directly, but then loose control over which get,post,put,delete I want this for.

**Comment by chriskapp** [comment]
Yes this is true, currently we have only a backend and consumer scope which cover all endpoints. For the next release I plan to create multiple scopes for the backend and consumer i.e. so that you have `backend.routes`, `backend.action`, etc. Then it is possible to configured also the backend and consumer rights more detailed. I have added also all rights related issue to the next 1.9 milestone see: https://github.com/apioo/fusio/milestone/3

**Comment by EvoPulseGaming** [comment]
Beautiful thank you

**Comment by chriskapp** [comment]
This is now implemented and will be included in the next release

**Comment by EvoPulseGaming** [comment]
XD
