### ISSUE TITLE
Allow logging of exact data sent, and reply of route.

### ISSUE THREAD

**Issue by EvoPulseGaming** [apioo/fusio#276]
I'm having an issue, where a server reply is crashing a production app on Android phones due to an invalid reply from the server (Fusio)

Is there a way, to log the data sent to the server, and the reply from the server for a particular route?

I was thinking, that where you define the route itself (get put post ECT) there could be a "Log this route" check box for each of the types (get put post ECT)

**Comment by EvoPulseGaming** [comment]
As a side note, it appears that http.client was lying to me (client side) and claimed it got an invalid response when network capturing A/B testing shows that the request never even got sent!

However this still could be useful, as I had to install and setup packet capturing on every device for testing

**Comment by chriskapp** [comment]
Hi, so in general we have the log panel where you can see every incoming request and also the request body. The reply is missing from the log since this would be to much for the log table to handle. Maybe we could think about some kind of debug mode but through the log table you can probably debug most use cases.
