### ISSUE TITLE
Connection pool

### ISSUE THREAD

**Issue by marll** [apioo/fusio#282]
Hi,
can i configure an connection pool?
Is a thread instantiated for each request?
I would like to use Fusio in an online architecture with a high parallelism.
Many Thanks

**Comment by chriskapp** [comment]
Hi, so since Fusio is build with PHP it follows the simple shared-nothing design, which means that there is no connection pool which you need to maintain every requests uses a separate connection. It also depends a little bit on your setup whether you use FPM or PHP as apache module. So Fusio can be easily used in a parallel setup.

**Comment by marll** [comment]
I use PHP module. If arrive ten transaction in a second Fusio starts 10 thread?
The action, in each thread, create and dispose the db connection.
Is correct this scenario?
Thanks

**Comment by chriskapp** [comment]
Yes this is right, but this also depends a little bit on your apache configuration how much simultaneous threads are allowed. If you reach the maximum number a request will block until the next thread becomes available. You can read more detail information at the apache documentation: http://httpd.apache.org/docs/2.4/en/mod/worker.html

**Comment by marll** [comment]
thanks a lot
