### ISSUE TITLE
Unable to login to /consumer/login

### ISSUE THREAD

**Issue by DarkScientist** [apioo/fusio#302]
Hi, 
when I try to login to /consumer/login using post request, it returns me an error : 

`An exception occurred while executing 'INSERT INTO fusio_app_token (app_id, user_id, status, token, refresh, scope, ip, expire, date) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [...] SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'scope' at row 1 in [...]`

If I remove scopes to the user into the user panel, that works but I'd like to perform my request without this problem.

Thanks for your help.

**Comment by chriskapp** [comment]
Hi, the problem is that the scope column length is to small, in the last release we have increased the length to 1024 s. https://github.com/apioo/fusio-impl/blob/master/src/Migrations/Version/Version20200220091902.php#L74 but I guess in your case this is also to small. You could simply increase the length of the column to fix the problem.

**Comment by DarkScientist** [comment]
Thanks for your answer !

So I just need to replace the `255` length by `1024` of the scope column through phpmyadmin ?

**Comment by DarkScientist** [comment]
Yeah that worked, thanks for your help !
