### ISSUE TITLE
Response Content-Type

### ISSUE THREAD

**Issue by dataforce-troy** [apioo/fusio#343]
@chriskapp 

Does Fusio support responses with content type other than 'application/json'?

For example, if I want the response to have a media type of 'application/octet-stream' to download a file.

How do I change the content type of the response in the API schema definition?

![Capture](https://user-images.githubusercontent.com/30102378/97823687-d2011a00-1d0d-11eb-88f8-e654bd71a5d8.PNG)

**Comment by chriskapp** [comment]
Hi, so in general inside your action you can simply return a different `Content-Type` header and set a binary body. But at the schema definition it is currently not possible to set a different content type.

**Comment by chgulden** [comment]
Support for general media types would be highly appreciated!

@chriskapp Can you please provide an overview of the required changes necessary to accomplish this?

**Comment by chriskapp** [comment]
Hi, sure so in general an action can already produce different content types, by simply setting the fitting `Content-Type` header and a string as response body. We have only a problem at the OpenAPI specification since there we currently always use `application/json`. To fix this we would need to somehow determine the Content-Type which an action produces, I have currently no good idea how to do this but since mostly APIs are based on JSON it is more an edge-case. If you have any ideas please let me know.
