### ISSUE TITLE
Documentation doesn't populate with details

### ISSUE THREAD

**Issue by Alvie** [apioo/fusio#366]
Hi, I am using Fusio 2.0.0 and am trying to get the documentation marketplace app to display the details of each endpoint. Looking into my browser's console / network requests, I can see that the documentations page does receive the data but for some reason it doesn't populate on to the page:

![image](https://user-images.githubusercontent.com/8447791/107362624-e608a480-6ad0-11eb-963f-a9b0b80b96f9.png)

In the console, there is this error but I cannot see a way of fixing it unfortunately:
![image](https://user-images.githubusercontent.com/8447791/107362821-2bc56d00-6ad1-11eb-9462-2ac80fc3ddf9.png)

The only change I have made is to set the url of the evid provider in apps/documentation/index.html:  
`evidProvider.setUrl('http://localhost/system/doc');`

**Comment by chriskapp** [comment]
Hi, yes this is currently an issue at the documentation app, we are currently redesigning this app for Fusio 2.0. If this is done we release a new version and you should able to update the app through the marketplace.

**Comment by Alvie** [comment]
> Hi, yes this is currently an issue at the documentation app, we are currently redesigning this app for Fusio 2.0. If this is done we release a new version and you should able to update the app through the marketplace.

Thank you for letting me know :)

**Comment by chriskapp** [comment]
so, we have just released a new version of the documentation viewer which is now compatible with Fusio 2.0, so you can update the app to get the latest version.

**Comment by Alvie** [comment]
Hi,

I have recently tried this again but now I am getting a new error that acts similarly to before:  
![image](https://user-images.githubusercontent.com/8447791/109016474-201b9e00-76ae-11eb-9d3d-c5af3ef06c1d.png)

I have tried this with the `marketplace:install` command as well as manually downloading version 1.0.2 and a couple other versions from the documentation app releases: https://github.com/apioo/fusio-apps-documentation/releases

So I am re-opening this issue as it seems it is related?

**Comment by Alvie** [comment]
@chriskapp I just realised I cannot re-open this issue. Would it be best for you to re-open this one or for me to create a new one? Thanks in advance

**Comment by chriskapp** [comment]
No problem, I can also reopen this issue. It looks like some request failed in your case, do also you use the latest version of Fusio 2.0.1?

**Comment by chriskapp** [comment]
Ok, we have just released a new version of the documentation app. In the latest version of Fusio we have added new links which are not available in older versions. We have now added a fix so that the latest version of the documentation app is compatible with older Fusio versions, so please try and test this latest version of the documentation app.

**Comment by udliveio** [comment]
Apologies for wasting your time with this. I think it was due to me not taking ownership of the public and cache folders whilst installing and deploying I believe. I have tried to reproduce the error but I am now unable to so I guess the fix worked! Thanks again :)

~~This was the latest version as I cloned directly from the Github. I did originally use the previous method with the 2.0.1 version for the schemas (where they are in .fusio.yaml -> resources/schemas.yaml -> resources/schema/modelname) as I thought this was an optional change.~~

~~Then I also removed these and redeployed with just the todo route with the "new" method but it still didn't work.~~ Either way, thank you for helping me with this issue

**Comment by Alvie** [comment]
Apologies for wasting your time with this. I think it was due to me not taking ownership of the public and cache folders whilst installing and deploying I believe. I have tried to reproduce the error but I am now unable to so I guess the fix worked! Thanks again :)

~~This was the latest version as I cloned directly from the Github. I did originally use the previous method with the 2.0.1 version for the schemas (where they are in .fusio.yaml -> resources/schemas.yaml -> resources/schema/modelname) as I thought this was an optional change.~~

~~Then I also removed these and redeployed with just the todo route with the "new" method but it still didn't work.~~ Either way, thank you for helping me with this issue
