### ISSUE TITLE
Scopes don't apply with user creation (POST /backend/user)

### ISSUE THREAD

**Issue by Alvie** [apioo/fusio#376]
I have noticed that roleId and scopes do not apply when a POST is sent to /backend/user with the creation of the user. Is this intentional behaviour? My workaround at the moment is to create the user with a POST to route above, then to get all users then extract the id from the first entry (as newest is at the top), the PUT to that user id the roleId and scopes. It'd be significantly better if it could be done in a single call unless I am misunderstanding why it is this way?

Thanks!

I have also attached screenshots of the POST and the GET requests to demonstrate that the scopes haven't applied

![image](https://user-images.githubusercontent.com/8447791/109156747-1efb7700-7769-11eb-9320-425112926ff1.png)
![image](https://user-images.githubusercontent.com/8447791/109157615-2707e680-776a-11eb-82ce-de2eca92ac9f.png)

**Comment by chriskapp** [comment]
Hi, yes so in Fusio 1.x the status was also the role, so we had a status for an admin and a consumer etc. This was a little bit limited since a user could not define new roles i.e. developer etc. which can only access specific parts of the backend. Because of this we have added in 2.x a new role id per user. A role can be configured at the backend and contains a specific set of scopes. So if you create a new user all scopes are take from the assigned role. Providing custom scopes to a user has no longer an effect. But it is still possible to adjust the scopes after the user was created.

**Comment by Alvie** [comment]
Gotcha, thank you for the detailed explanation, that really helped me to understand it :)
