### ISSUE TITLE
Question: fusio_token.json in home directory

### ISSUE THREAD

**Issue by Alvie** [apioo/fusio#381]
Hello, I have noticed on the newer version of Fusio, it does not use a hard-coded Bearer token in the fixture. Instead there is a variable set in the ApiTestCase that can be accessed as such: `$this->accessToken`.

I took a look through the vendor files and noticed a reference to the token being saved in a JSON file in the home directory:
```
return $homeDir . '/fusio_token.json';
```

I was wondering why it is saved in the home directory and not somewhere within the folder. It seems that the file being in the home directory can be easily accidentally deleted or similar? I am just trying to understand the reasoning behind this.

Thanks!

**Comment by chriskapp** [comment]
Hi, so the token gets stored by the [CLI client](https://github.com/apioo/fusio-cli) which is in general also a standalone project and which can be used independently on a client to control a Fusio instance. But the CLI is also by default included at the Fusio installation so that a user does not need to extra install this CLI tool. Because of this we have used the home dir where we cache the access token.

Regarding the access token from the TestCase this is requested dynamically on each test call, so you dont need to modify this value.

**Comment by Alvie** [comment]
Thanks for the explanation
