### ISSUE TITLE
[QUESTION] What can a user do with backend.account scope (other than update password)?

### ISSUE THREAD

**Issue by Alvie** [apioo/fusio#404]
I would like a user to be able to update passwords and wish to do this via the API. I see that there is a route for this: `/backend/account/change_password`

But it requires the user to have the `backend.account` scope attached to it as it updates the password for the username in the login token. Are there any downsides to this? What else would the user be able to do with this scope?

Thanks in advance!

**Comment by chriskapp** [comment]
Hi, yes the `backend.account` scope is only for changing the account of the password and the scope is not used at other routes. If you want that a user can change his password I would recommend to use the `/consumer/account/change_password` which has the `consumer.user` scope assigned, so that you dont need to give a user a backend scope.

**Comment by Alvie** [comment]
> Hi, yes the `backend.account` scope is only for changing the account of the password and the scope is not used at other routes. If you want that a user can change his password I would recommend to use the `/consumer/account/change_password` which has the `consumer.user` scope assigned, so that you dont need to give a user a backend scope.

Thanks, that's great!
