### ISSUE TITLE
Route path fragments in Cli adapter action

### ISSUE THREAD

**Issue by tomgrice** [apioo/fusio#421]
Hi guys
There is probably a more elegant way to go about it, but is there any way to pass uri fragments to the cli?
I am trying to pass url data to a powershell script. So for example the url http://example.com/test/:myvariable

Which would then call via the Cli:
`pwsh -Command "Write-Host \"$myvariable\""`

Which would simply echo whatever text was put in the /:myvariable fragment

Is there any way to get something like this to work? Or a more elegant solution?

Thanks

**Comment by chriskapp** [comment]
Hi, so currently this is not possible because of security issues, since this would allow an attacker to alter your command. But we could maybe pass those params via ENV variables then you could access those data in your script. You can find the cli adapter here: https://github.com/apioo/fusio-adapter-cli/blob/main/src/Action/CliEngine.php#L110
Would this be an solution for your case, in poweshell it looks like you can access env avriable via `$Env:<variable-name>`

**Comment by chriskapp** [comment]
So I was just curious by this idea and build a first PR s. https://github.com/apioo/fusio-adapter-cli/pull/1 which basically passes the uri fragment, query parameters and headers as env variables to the command which you execute, in general I think this is a great idea but feel free to check whether this works for your case.

**Comment by tomgrice** [comment]
Hi Christoph, thanks for replying!

I probably over-simplified my issue before, of course in my use case I would perform some validation and sanitisation checks on the input so no kind of command/code injection was possible. I understand the security concerns and as I think about it your solution would still work perfectly. Indeed you can call Env variables directly in powershell.

Going forward I will probably look into writing a custom Action which invokes a pwsh cli and runs either a script or a command. Your solution is great in the meantime though!

I should probably rewrite my scripts in php for this haha!

**Comment by chriskapp** [comment]
This PR was merged at the 2.1.5 release
