### ISSUE TITLE
"Entry successful deleted" incorrectly reported

### ISSUE THREAD

**Issue by ratsey** [apioo/fusio#429]
@chriskapp - could well be similar to the last issue I had with all "Passthru" options selected. A delete operation from my Angular API will report a success message but not actually remove the record from MariaDB:

Route
![image](https://user-images.githubusercontent.com/7027608/147860799-8f538814-55a5-41c0-ae41-1c9b48578ed4.png)

![image](https://user-images.githubusercontent.com/7027608/147860758-0ab7850d-ab5f-4d1c-8991-bbd11b24d165.png)

Action
![image](https://user-images.githubusercontent.com/7027608/147860830-f83dc1a0-1f4e-4c99-939e-b472eae910e1.png)

If I execute the same payload using Designer, the same message is returned and the row is actually removed from the database.

payload
`{ "id": 3 }`

Response:
```
{
	"success": true,
	"message": "Entry successful deleted"
}
```
I do have other Delete actions working with the same configuration. The only real difference here is that the table is a many-many resolving table but I did convert it to have a dedicated new PK ID. The addition FK constraints should not impact a delete operation but may be causing some 'internal' issues with the Fusio code.

![image](https://user-images.githubusercontent.com/7027608/147860887-1fde8080-286a-4388-89bb-b44c3dbe24be.png)

Minor point of improvement (with full appreciation that English is not your native language!), the message should read 'Entry successfully deleted"

**Comment by chriskapp** [comment]
Hey, regarding the delete, so Iam not sure whether this is an issue regarding Fusio, the delete action basically only triggers a delete based on the provided primary key s. https://github.com/apioo/fusio-adapter-sql/blob/master/src/Action/SqlDelete.php#L68 If your table has no PK you should get an error message "Primary column not available". Regarding the error message, no problem, we can simply adjust the error message, we should do this then probably for all create/update and delete actions.

**Comment by ratsey** [comment]
That's what is confusing here - the table does have a PK called 'id' as seen in the schema diagram snippet above. Issuing a `DELETE` against the table using my Angular app or Insomnia client does not delete the row (it's still there in the database) but gives a success operation response. If I perform the same DELETE using the UI Designer, I get the same sucess operation response, but the row is deleted from the database. So there's something different in how the REST call is made using Insomnia and how the UI Designer makes the call. 

```
        $connection->delete($table->getName(), [$key => $id]);

        return $this->response->build(200, [], [
            'success' => true,
            'message' => 'Entry successful deleted'
        ]);

```

I think this section of code is not working as expected. My PHP skills are very poor but I might have a go at expanding this to see what's going on. I think there's an assumption here that the `$connection->delete` operation worked.

**Comment by ratsey** [comment]
I've found the problem. A fun one.  My route is `campaign/:id/shippingoptions`. Even though my delete operation payload is 

`{ "id": 7 }`

I'm calling it from a URL of `campaign/25/shippingoptions`. This is a request to delete a row with PK ID=7. The `25` value is largely arbitrary here BUT it is being picked up from `$id    = (int) $request->get('id');` and not from the JSON payload.

Problem resolved. User error.

**Comment by ratsey** [comment]
I was going to close out, but I think there's an opportunity to enhance the code here. Check the return value from the delete operation and provide appropriate feedback in the response. Suggest something like `$returnValue . ' row(s) deleted`. If the value is 0, then return something other than HTTP 200 since it's not really a succesful operation if a delete request didn't delete something.

**Comment by chriskapp** [comment]
Ok, so great that you have found the issue and indeed it would be better to handle this case, so the delete method already returns an int containing the affected rows. I think the best behaviour would be to return an 404 Status-Code in case the int is 0 since this means that the resource which we want to delete does not exist. Then we also dont need to return the affected rows since the delete is on success always 1 because we execute the delete on the primary key.

**Comment by ratsey** [comment]
I like that idea - although a `400 Bad Request` might be a better option, since 404 would indicate that the actual end point is not valid. Are you open to pull requests? If so, I might have a go at contributing!

**Comment by chriskapp** [comment]
Sure, please feel free to make a first PR. I thought about an 404 since if you visit an url i.e. `GET` to `/entry/10` and the entry is not available you get a 404 and if you make a `DELETE` to `/entry/10` and the entry is not available you would also get a 404, I think this would be a consistent behaviour since in both cases the resource is not available. In my view `400` indicates more that the user has provided an invalid request body but in case of `DELETE` we dont have a request body. But REST is of course not a strict specification and there are many ways to use the status codes.

**Comment by chriskapp** [comment]
@ratsey FYI we are currently on our way to move the entire code base to PHP 8.0, in this process we have also adjusted the action s. https://github.com/apioo/fusio-adapter-sql/blob/master/src/Action/SqlDelete.php#L60 so this behaviour gets then shipped with the next major release, but this may also take some time since we also plan to move our backend app from AngularJS to a new Angular version, which requires also some work :) ... but please feel free to make comments or suggest changes to the action.
