### ISSUE TITLE
SQL keyword collision

### ISSUE THREAD

**Issue by ratsey** [apioo/fusio#431]
My order management system has a table called 'order' - perhaps in hindsight not the best name, but the system has been around for years.

Trying to migrate to use the new Fusio table driven actions, I get SQL errors when trying to insert new values since the table name `order` must be wrapped in back-ticks to encode it. Can all table references be encoded?  MariaDB takes back-ticks, SQL server takes square brackets, etc.

```
"An exception occurred while executing 'INSERT INTO order (customer_id, category_id,  ...:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order (customer_id, category_id, source_system, source_order_id, sales_total,...' at line 1 in /home/xxxx/xxxx/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 98"
```

The working syntax would be ``INSERT INTO `order` (customer_id, category_id, ...``

**Comment by chriskapp** [comment]
Hey Ratsey, so the action itself uses also only the insert/update and delete methods of our database abstraction layer s. https://github.com/apioo/fusio-adapter-sql/blob/master/src/Action/SqlInsert.php#L52 the library itself does not escape those identifiers since quoting can be tricky i.e. for mysql you can use backticks but also double quotes per SQL standard and like you mentioned other systems have also other quoting. I would suggest that you simply create an action for your case where you add the quoting.

**Comment by ratsey** [comment]
@chriskapp  Yes, digging some more and it seems quite a common 'complaint' about DBAL in general. Consensus seems that it's too difficult, so the Doctrine team didn't bother trying.  I'll try a custom action instead, per your suggestion.

**Comment by ratsey** [comment]
@chriskapp I'm recoding the front end - I may as well do some refactoring on the back end too and just rename it `orders` to save myself future headaches!
