### ISSUE TITLE
How to use UserService

### ISSUE THREAD

**Issue by subangkit** [apioo/fusio#47]
In my case is fusio failed to send registration email which has token for activation user, so how to resend this email, or use User Service from Fusio/Impl?

**Comment by k42b3** [comment]
Hi, mhh at the moment it is not possible to resend this message. But you can simply change the status of the registered user inside the Fusio backend to i.e. consumer. Then the user is activated.

**Comment by subangkit** [comment]
Hi, so sad, so why every I register new user, I did not receive activation email? is there something wrong?

**Comment by subangkit** [comment]
Hi, sorry my mistake need to set it false `'psx_debug'               => true,` . And maybe you need allow user to send email with debug is true, coz to track maybe if user setting wrong email configuration.

**Comment by k42b3** [comment]
Hi yes if `psx_debug` is true Fusio does not send any mails. We dont want to send mails in this case since this mode is only for debugging. If you like you can change the behaviour in the `Fusio\Impl\Mail\TransportFactory` class. So I will close this issue, if you have any further questions please let me know.
