### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by Draeli** [apioo/fusio#474]
![image](https://user-images.githubusercontent.com/2436548/193934670-7cd9779d-7532-465f-873f-5de8aaecf411.png)
URL given is as absolute and not relative to current URL :(
All link for this page are with the same problem.

**Comment by Draeli** [comment]
I add this : 
![image](https://user-images.githubusercontent.com/2436548/193992550-baf948d8-0ae4-4d84-986d-ad4269471a11.png)
I guess the problem is more generic

**Comment by chriskapp** [comment]
Hi @Draeli, so in general you can edit the content of the developer portal also at the backend s.
![image](https://user-images.githubusercontent.com/2505846/194134282-2380e18a-025b-4ab1-942c-4110b458c73f.png)

and adjust all urls etc. since in most cases you need to customize the developer portal for your case. But it should indeed also work out of the box, so we could think about using relative urls like you mentioned. All default content gets installed on initial installation through the following files s.
https://github.com/apioo/fusio-impl/tree/master/src/Migrations/resources

**Comment by chriskapp** [comment]
I have also just created a PR to fix those links s.
https://github.com/apioo/fusio-impl/pull/30/files

**Comment by chriskapp** [comment]
The PR was just merged and the changes are then included in the next release
