### ISSUE TITLE
Can not create Operation again with the same http_path after it was deleted

### ISSUE THREAD

**Issue by wdhwang** [apioo/fusio#509]
Steps:
1. Create Operation with http_path /test
2. Delete Operation with http_path /test
3. Create Operation with http_path /test

Result: Can't create Operation, error ocurred "An operation exists already with the same HTTP method and path".

Resolve:
1. Issue the command "delete from fusio_operation where status='0'" to MySQL
2. Create Operation with http_path /test successfully

**Comment by chriskapp** [comment]
Hi @wdhwang, if you delete an operation we only set the status to deleted "0", you can easily restore the operation under the System / Trash panel. We don`t execute an actual delete since the operation id is referenced in several logs etc. and then we would loose this reference. It has also the advantage that you can simply restore the operation in case the delete was a mistake.

**Comment by wdhwang** [comment]
@chriskapp Got it. Thanks for your prompt reply.
