### ISSUE TITLE
impossible to log-in on fusion panel

### ISSUE THREAD

**Issue by andrekutianski** [apioo/fusio#78]
I recently installed version 0.9.9, I performed all the documentation steps but I can not log in with the created user.

I re-install manually and through composer, but the same error occurs. In the database, the user has been created. No PHP errors or alerts. I using PHP 7.0

![screenshot-2017-10-17 fusio](https://user-images.githubusercontent.com/5316107/31694710-85907fb2-b384-11e7-8eb8-15fc760ee9bd.png)

**Comment by zaniar** [comment]
you should use **username**, not email. Except if you set your username the same as your email, which I don't think the current version of fusio allowed that.

**Comment by andrekutianski** [comment]
@zaniar I have tried with email and username, #66

**Comment by k42b3** [comment]
Hi, this looks like your webserver does not forward the `Authorization` header to Fusio. If you use Apache as webserver do you have `mod_rewrite` enabled? Otherwise please take a look at: http://fusio.readthedocs.io/en/latest/installation.html#backend which contains a list of possible login problems. If you think this is another issue please let me know.

**Comment by andrekutianski** [comment]
Probably this issue is because of my environment. I 'm using cPanel CloudLinux with Apache 2.4 that compile `mod_rewrite` [dynamically](https://forums.cpanel.net/threads/mod_rewrite-with-ea4.554691/#post-2241361).

I tested the `mod_rewrite` and all seems good ( [here](https://eunarede.info/test) and [here](https://eunarede.info/htaccess_tester.php) ). The `cache/` folder is with the correct permissions. 

I do not know what else to do :cry:

**Comment by k42b3** [comment]
Ok, I have not installed Fusio on a cPanel CloudLinux yet but I think it should be doable. So in order to debug this, could you upload the following debug script `test.php` to your server and execute it:

```php
<?php
if (isset($_GET['send'])) {
	header("Content-Type: text/plain");
	var_dump($_SERVER);
	exit;
}
?>
<html>
<head>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
</head>
<body>
<pre id="response"></pre>
<input id="btn" type="button" value="Debug">
<script type="text/javascript">
$("#btn").click(function(){
	$.ajax("?send=1", {
		beforeSend: function(xhr){
			xhr.setRequestHeader("Authorization", "Bearer foobar");
		},
		success: function(data){
			$("#response").text(data);
		},
		error: function(xhr, error){
			$("#response").text(error);
		}
	});
	return false;
});
</script>
</body>
</html>
```

This basically sends an AJAX request with a custom `Authorization` header. The response should then include an `HTTP_AUTHORIZATION` key. If such an key is not available we know that there is a problem with the `Authorization` header otherwise we need to look into other cases.

**Comment by koswarabilly** [comment]
i have an authentication failed with error "Failed to load resource: the server responded with a status of 404 (Not Found)" fusio/public/index.php/backend/token

i also have a blank 127.0.0.1 with error of internal server error 500

**Comment by k42b3** [comment]
I will close this issue since it looks like there is nothing more todo here. The login problem was probably related to the server configuration. More information to troubleshoot such problems at: http://fusio.readthedocs.io/en/latest/installation.html#backend
If you still feel that there is a problem please reopen the issue.
