### ISSUE TITLE
@FormParam not in type of 'application/x-www-form-urlencoded'

### ISSUE THREAD

**Issue by koswarabilly** [apioo/fusio#89]
i am getting this error
is there a way to fix this?
![screenshot from 2017-11-02 11-08-44](https://user-images.githubusercontent.com/29243760/32309437-385138fe-bfbe-11e7-9038-c68282372cf1.png)

my question is 
how do you change your content-type because when i post to this url it need x-www-form-urlencoded to get responses

**Comment by k42b3** [comment]
From the server response it looks like the client has not send a proper `Content-Type` header. Which action do you use to send the HTTP request? If you have used the normal `HTTP-Processor` then you need to send also a proper `Content-Type` header to the Fusio endpoint. Maybe you can use an external REST tool to send a fitting HTTP request to the Fusio endpoint, in order to test whether this works.

The action designer has at the moment no field to configure also HTTP headers, but this would be a good new feature.

**Comment by zaniar** [comment]
If you still want to use `HTTP-Processor` action class, you can not do it for now. You need to wait until the header field is implemented into `HTTP-Processor`.

The alternative solution are:

1. Modify the HTTP adapter yourself. Either forking it or edit it directly in `vendor` directory (for quick & dirty fix).

2. Use `PHP-Processor` action class. Create a Connection with `HTTP` as the class. `$connector->getConnection('your-connection-name')` will return `GuzzleHttp\Client`. Look up to [Guzzle documentation](http://docs.guzzlephp.org/en/stable/request-options.html#headers) on how to make a request.

**Comment by koswarabilly** [comment]
Which part in vendor should i change? It will be a mess if i did something stupid, isn't it?

**Comment by zaniar** [comment]
Look at `vendor/fusio/adapter-http/src/Action/HttpEngine.php`. You can focus on `$headers` variable. Add your header to `$headers` array.

I still recommend alternative number 2 though.

**Comment by k42b3** [comment]
Just for your information I have added (https://github.com/apioo/fusio-backend/commit/a49e7dd302980390212a4fbf035415d866d18672) a headers field to the designer so that its possible to set custom HTTP headers. The update is then included in the next release. If you want to use the header field now you can also simply update the app from the repository.

**Comment by koswarabilly** [comment]
btw thankyou @zaniar and @k42b3 ,but how do you update the app from your repo?

**Comment by k42b3** [comment]
You're welcome, basically you can download the latest version of the `fusio.min.js` and `fusio.min.css` file from the repository (https://github.com/apioo/fusio-backend/tree/master/dist) and replace those files in the `public/fusio` folder.

**Comment by koswarabilly** [comment]
i have replace fusio.min.js and fusio.min.css in the public/fusio but nothing seems to have changed, please take a look at this screenshot

![screenshot from 2017-11-06 08-11-53](https://user-images.githubusercontent.com/29243760/32421349-2df41ba6-c2ca-11e7-9835-fa389e18b90c.png)

i can't find any header field in action form which make me still get the same error (500).
where do i pass the parameter? did i do it right with the right format in the screenshot?

**Comment by zaniar** [comment]
It should be in `public/fusio/dist`.

If it is still not working. Try to disable cache on your web browser.

**Comment by koswarabilly** [comment]
thankyou @zaniar it works now but take a look what error i still get

![screenshot from 2017-11-06 09-28-25](https://user-images.githubusercontent.com/29243760/32422760-dca9ef36-c2d4-11e7-9446-4d8fe9e2e874.png)

i have changed the header type.
is it normal that the body: do not have any field?

**Comment by koswarabilly** [comment]
i close this issue as it is out of topic already..
