### ISSUE TITLE
/backend/scope/:id did not return all entries

### ISSUE THREAD

**Issue by zaniar** [apioo/fusio#90]
I got 20 entries in table `fusio_scope_routes` with `scopeId` = 4.
But  `/backend/scope/4` only give 16 entries.

**Comment by k42b3** [comment]
This is true, the sub query which fetches the assigned routes for the scope has by default a limit of 16. But this is a bug and the query should return all assigned routes.

**Comment by k42b3** [comment]
This problem is fixed through the commit https://github.com/apioo/fusio-impl/commit/50f72ac9a4a2c86cc621d4c154cf5756249308d1

**Comment by zaniar** [comment]
I tried to change that line. It did not change anything. It is still returned 16 entries.

I also tried to updated `fusio/impl` to `dev-master`. The result is the same.

Did I miss something?

**Comment by zaniar** [comment]
I change it to

```php
'routes' => $this->doCollection([$this->getTable(Table\Scope\Route::class), 'getAll'], [0, 1024, new Reference('id'), Sql::SORT_DESC, new Condition(['scopeId', '=', $id])], [
```

then it worked as it should be.

**Comment by k42b3** [comment]
The fix works only in a combination with another fix of the sql library (https://github.com/apioo/psx-sql/commit/abd55eb69aa6ae368e061b771facbaeaba956ea5). I would guess that in your case you have not installed the latest version `v2.1.0`. Your fix should also work but the arguments of the `getAll` method are always `startIndex, count, sortBy, sortOrder, condition`. In your case you would use `new Reference('id')` as `sortBy` field which is never a valid column since `new Reference('id')` gets replaced with the actual scope id of the outer query.

**Comment by zaniar** [comment]
Updated `psx/sql` and now it worked as it should be. :+1:
