### ISSUE TITLE
Parameter not read 

### ISSUE THREAD

**Issue by koswarabilly** [apioo/fusio#92]
from my last issue which is content-type have been fixed [#89](https://github.com/apioo/fusio/issues/89) ,but come new problem which is parameter
i want to put some parameter when i try to get respond from certain url

![screenshot from 2017-11-06 15-08-05](https://user-images.githubusercontent.com/29243760/32431037-655fb39a-c304-11e7-940a-8f14a4d4153f.png)

when i try to execute this come out as error

![screenshot from 2017-11-06 15-11-23](https://user-images.githubusercontent.com/29243760/32431140-c69639d6-c304-11e7-99b7-f1fc470f059d.png)

is it the right format to pass in parameter? 
because me and my colleague discover that fusio pass the right header content-type but it do not pass the right parameter
or am i getting the wrong assumption?

**Comment by zaniar** [comment]
Could you try to make a request to `http://192.168.51.45:8787/erp-ws-main/ws/postdata` using `curl`, `postman`, `insomnia`, or something else?

I think this is not Fusio's issue. More likely an issue with your target server.
Do you really following the manual about how to connect to your target server correctly?

**Comment by koswarabilly** [comment]
I tried it with postman and i get a result
The url and parameter are copied from postman
As i say if the url from the SS and the parameters from the SS are linked with '?' It is the url i copied from postman

**Comment by k42b3** [comment]
Mhh ok I think the problem is that you want to send your data encoded as `application/x-www-form-urlencoded`. The HTTP action currently only sends data as `application/json` to the endpoint. That being said you can send `application/x-www-form-urlencoded` content to Fusio but the HTTP action will then send the request as `application/json` to your endpoint. If you remove the `Content-Type` header and simply enter `{"foo": "bar"}` as body, what is the response of the server?

**Comment by koswarabilly** [comment]
i tried postman and insomnia and both successfully return a result here are the screenshots
@zaniar 
![screenshot from 2017-11-07 08-03-15](https://user-images.githubusercontent.com/29243760/32475008-30a1d266-c3a2-11e7-8963-39f8e198ede7.png)

![screenshot from 2017-11-07 09-58-57](https://user-images.githubusercontent.com/29243760/32475037-511cc4f6-c3a2-11e7-8c19-7a3eb5675473.png)

@k42b3 
do you mean it like this?i don't change the url,parameters, & method
![screenshot from 2017-11-07 10-00-50](https://user-images.githubusercontent.com/29243760/32475090-a12c5dbc-c3a2-11e7-904d-c7f06c6eafd2.png)

**Comment by k42b3** [comment]
Ok, yes then this is the problem, that we always send the body JSON encoded. I have started to improve the HTTP Adapter so that you have beside the URL field another select box `Content-Type` where you can select the content type of the request payload. The adapter uses the the options `json` or `form_params` key in the guzzle request. I will let you know if this is implemented. Then you need to add the `responseCode`, `responseParam` and `authParam` Field to the `body`.

**Comment by koswarabilly** [comment]
thankyou @k42b3

**Comment by k42b3** [comment]
So I have update the HTTP adapter. If you dont want to wait for the next release you could also update the adapter through composer, i.e. simply using the following command:

```
composer update fusio/adapter-http
```

**Comment by k42b3** [comment]
The latest release includes now also the updated http adapter
