### ISSUE TITLE
Custom /authorization/token & /authorization/revoke

### ISSUE THREAD

**Issue by zaniar** [apioo/fusio#94]
I need to run my own additional logic when client accessing `/authorization/token` & `/authorization/revoke`.

How could I do that?

As far as I know I can not do this in a way like creating custom register end point (my previous issue #70).

**Comment by k42b3** [comment]
So creating a custom endpoint and using a service is one option. But it is also possible to use the event system. The event system fires specific actions i.e. if a user creates an action or generates an access token etc. I.e. to add custom code everytime a token is generated you can use the following code in the `container.php` file:

```php
$container = new Fusio\Impl\Dependency\Container();
$container->setParameter('config.file', __DIR__ . '/configuration.php');

/** @var Symfony\Component\EventDispatcher\EventDispatcher $eventDispatcher */
$eventDispatcher = $container->get('event_dispatcher');

$eventDispatcher->addListener('app.generate_token', function(\Fusio\Impl\Event\App\GeneratedTokenEvent $event){
    // @TODO custom code
});

```

But through those events it is never possible to changes the response of an endpoint. You can only add additional logic i.e. send an email.

Unfortunately this whole event system and the available events are currently not described in the documentation but you can take a look at the folder `src/Event` which contains classes with all available event names. But in the future it would be great to add a new chapter i.e. `Extension` to the documentation where we explains howto extend and customize Fusio.

FYI for the revoke case we have already an event `app.remove_token` but the `/authorization/revoke` endpoint does not trigger this event which is basically a bug and I will fix this in the next release. So please let me know whether this helps you to extend Fusio for your use case.

**Comment by zaniar** [comment]
I see.

Is there any way to have additional response (changing the response) for `/authentication/token` ? I would like to include some user data along with the token.

I know I can make another request after I got `access_token`, but I wonder if I can do it in one request.

**Comment by k42b3** [comment]
Mhh I think this is currently not "easy" possible. Which user information do you want to include in the response, simply the username or also other custom properties?

Otherwise it is possible, you could change the controller of the endpoint in the `fusio_routes` table to a custom implementation. Then you could create complete customized responses.

**Comment by zaniar** [comment]
It is custom data in other database outside fusio.

I use `/authentication/token` as login endpoint for my app. If the login is successful I want to return some data alongside the token.

Currently, I make a login request to `/authentication/token` then make another request to other endpoint to deliver the custom data.

**Comment by k42b3** [comment]
So for your information, the latest release includes now the fix that the event is properly triggered. 

Regarding the issue to return a custom response, in general the `/authentication/token` endpoint is an OAuth2 endpoint to return an access token for an user. So it is important that the endpoint follows the [OAuth2](https://tools.ietf.org/html/rfc6749#section-4.1.4) specification. I think it would be not good if its possible to modify the response since this could cause als security problems.

If I think about it, currently each app has also a `Parameters` field where you can store arbitrary key value pairs for an app. Would it be useful for you if we also return such data in the response?

**Comment by zaniar** [comment]
If there is an convention or specification for this matter, it is fine to leave it as it is now, I think.

I don't know abut returning `Parameters`. My current case is not about including app data , but user data. So I can not comment about it.

**Comment by k42b3** [comment]
Ok, then I will close this issue for now.
